---
- name: install_tspider.yml
  import_playbook: install_tspider.yml

- name: sync_tspider_schema.yml
  import_playbook: sync_tspider_schema.yml

- hosts: tspider
  tasks:
    - name: add tspider node to tdbctl
      shell: |
        USERPASS_OPTS="-u{{tendbcluster_user_admin}} -p{{tendbcluster_user_admin_pass}}"
        mysql $USERPASS_OPTS -h{{tdbctl_host}} -P{{tdbctl_port}} -e "replace into mysql.servers (Server_name,Host,Port,Username,Password,Wrapper) values('{{Server_name}}', '{{tspider_host}}', '{{mysql_port}}', '{{tendbcluster_user_admin}}', '{{tendbcluster_user_admin_pass}}', 'SPIDER'); tdbctl flush routing;"
        echo "replace into mysql.servers (Server_name,Host,Port,Username,Password,Wrapper) values('{{Server_name}}', '{{tspider_host}}', '{{mysql_port}}', '{{tendbcluster_user_admin}}', '{{tendbcluster_user_admin_pass}}', 'SPIDER'); tdbctl flush routing; " > /tmp/add_tspider.sql
      vars:
        tspider_host: "{{ansible_host}}"
        tspider_port: "{{mysql_port}}"
        tdbctl_host: "{{hostvars[groups['tdbctl'][0]]['ansible_host']}}"
        tdbctl_port: "{{hostvars[groups['tdbctl'][0]]['mysql_port']}}"
        Server_name: "SPIDER{{groups.tspider.index(inventory_hostname)}}"
      delegate_to: "{{ groups['tdbctl'][0] }}"
