---
- hosts: tendb
  tasks:
    - name: grant privileges for tendb
      include_role: 
        name: tendb
        tasks_from: grant.yml

- hosts: tspider
  tasks:
    - name: grant privileges for tspider
      include_role: 
        name: tspider
        tasks_from: grant.yml

- hosts: tdbctl
  tasks:
    - name: grant privileges for tdbctl
      include_role: 
        name: tdbctl
        tasks_from: grant.yml
