---
- hosts: tspider
  tasks:
    - include: check_config.yml

- hosts: tspider
  roles:
    - role: tspider

- hosts: tspider
  tasks:
    - name: grant privileges for tspider
      include_role:
        name: tspider
        tasks_from: grant.yml
