---
#- block:
#  - name: Ensure ntp packages are installed.
#    yum: name=ntp state=installed
#
#  - name: Update time on server.
#    shell: ntpdate 0.asia.pool.ntp.org && hwclock --systohc
#    ignore_errors: true
#    
#  - name: Change ntpd server on ntp.conf.
#    template: src=ntp.conf.j2 dest=/etc/ntp.conf backup=yes
#    notify: restart ntpd
#  tags: ntp
  
- name: Change nofile limits.
  lineinfile: dest=/etc/security/limits.conf line={{ item }}
  with_items:
    - '* - nofile 200000'
    - '* soft nofile 200000'
    - '* hard nofile 200000'
  tags: limits

- name: Shutdwon selinux.
  replace: dest=/etc/selinux/config regexp=^SELINUX=enforcing replace=SELINUX=disabled
  tags: selinux

- name: setenforce off
  command: setenforce 0
  ignore_errors: yes
  
- block:
  - name: Shutdown transparent hugepage.
    shell: echo never >> /sys/kernel/mm/transparent_hugepage/enabled && echo never >>  /sys/kernel/mm/transparent_hugepage/defrag
    
  - lineinfile: dest=/etc/rc.local line={{ item }}
    with_items:
     - echo never >> /sys/kernel/mm/transparent_hugepage/enabled
     - echo never >> /sys/kernel/mm/transparent_hugepage/defrag
  ignore_errors: yes
  tags: hugepage

#- name:  clean rpmdb
#  shell: |
#    cd /var/lib/rpm ; rm -f __db.* ; rpm --rebuilddb ; yum clean all ; yum makecache
#  ignore_errors: yes
 
- name: Ensure gcc packages are installed.
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - gcc
    - gcc-c++
    - libtool
    - make
    - automake
    - libaio
    - vim
    - wget
    - telnet
    - git
    - unzip
    - bzip2
  tags: gcc
  ignore_errors: yes
  
- name: Set vm.overcommit_memory to 1 in /etc/sysctl.conf.
  sysctl:
   name: vm.overcommit_memory
   value: 1
   state: present
  tags: overcommit_memory

- name: Set vm.swappiness to 1 in /etc/sysctl.conf.
  sysctl:
   name: vm.swappiness
   value: 1
   state: present
  tags: swappiness

- name : update bash
  yum : name=bash state=latest
  ignore_errors: yes

- name: Set net.ipv4.ip_local_port_range to 25000 50000 in /etc/sysctl.conf.
  sysctl:
   name: net.ipv4.ip_local_port_range
   value: 25000 50000
   state: present
  tags: ip_local_port_range
  ignore_errors: yes

- name: Set net.ipv4.tcp_tw_reuse=1 and net.ipv4.tcp_tw_recycle=1 in /etc/sysctl.conf.
  sysctl:
   name: "{{ item }}"
   value: 1
   state: present
  with_items:
    - net.ipv4.tcp_tw_reuse
    - net.ipv4.tcp_tw_recycle
  ignore_errors: yes
  tags: ipv4_tcp_reuse
