---
- name: configure | Templating privileges to tendb
  template:
    src: "grant_tendb.sql.j2"
    dest: "/data/grant_tendb.{{mysql_port}}.sql"
  when: "'tendb' in group_names"

- name: configure | Apply privilegs to tendb
  shell: |
    # mysql -h127.0.0.1 -P20000 -u{{tendbcluster_user_admin}} -p{{tendbcluster_user_admin_pass}} < /data/grant_tendb.sql
    mysql -f -uroot --socket {{mysql_data_dir}}/mysql.sock < /data/grant_tendb.{{mysql_port}}.sql
    #rm -f /data/grant_tendb.{{mysql_port}}.sql
  when: "'tendb' in group_names"

- name: configure | Templating privileges to tspider
  template:
    src: "grant_tspider.sql.j2"
    dest: "/data/grant_tspider.{{mysql_port}}.sql"
  when: "'tspider' in group_names"

- name: configure | Apply privileges to tspider
  shell: |
    mysql -f -uroot --socket {{mysql_data_dir}}/mysql.sock < /data/grant_tspider.{{mysql_port}}.sql
    #rm -f /data/grant_tspider.{{mysql_port}}.sql
  when: "'tspider' in group_names"

- name: configure | Templating privileges and routes
  template:
    src: "{{ item }}"
    dest: "/data/{{ item }}.{{mysql_port}}"
  with_items:
    - grant_tdbctl.sql.j2
    - flush_tdbctl.sql.j2
  when: "'tdbctl' in group_names"

- name: configure | Flush privileges and routes to tspider
  shell: |
    mysql -f -uroot --socket {{mysql_data_dir}}/mysql.sock < /data/{{ item }}.{{mysql_port}}
    #rm -f /data/flush_tdbctl.{{mysql_port}}.sql
  with_items:
    - grant_tdbctl.sql.j2
    - flush_tdbctl.sql.j2
  when: "'tdbctl' in group_names"
