---
- name: install | Donwload mysql tarball from fileserver
  get_url:
    url: '{{ tdbctl_pkg_url }}'
    dest: "/data/{{ tdbctl_pkg_tar }}"
    force: no
    checksum: "{{ 'md5:' + tdbctl_pkg_md5 if checksum_enabled else '' }}"

- name: install | Untar package
  shell: sleep $[ ( $RANDOM % 3 )  + 1 ]s ; test -e /usr/local/{{ tdbctl_pkg }} || tar --skip-old-files --no-overwrite-dir -xf /data/{{ tdbctl_pkg_tar }} -C /usr/local/
  args:
    creates: "/usr/local/{{ tdbctl_pkg }}"

- name: install | Create symbolic link to /usr/local/tdbctl
  file:
    src: "/usr/local/{{ tdbctl_pkg }}"
    dest: "{{tdbctl_basedir}}"
    state: link
  ignore_errors: yes

- name: install | Make mysql dirs
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    recurse: yes
  with_items:
    - "{{ mysql_log_dir }}/{{ mysql_port }}"
    - "{{ mysql_conf_dir }}"
    - "{{ mysql_home_dir }}"
    - "{{ mysql_data_dir }}"
    - "{{ mysql_data_dir }}/data"
    - "{{ mysql_data_dir }}/tmp"
    - "{{ backup_dir }}"

- name: configure | Setup my.cnf file.
  template:
    dest: "{{ mysql_conf_dir }}/my.cnf.{{mysql_port}}"
    src: my.cnf.tdbctl.j2
    mode: 0644

- name: Ensure mysql_home user.group
  file:
    path: "/usr/local/{{ tdbctl_pkg }}"
    owner: mysql
    group: mysql
    recurse: yes

- name: initialize mysql home
  shell: |
    cd {{tdbctl_basedir}}
    ./bin/mysqld --defaults-file={{mysql_conf_dir}}/my.cnf.{{mysql_port}} --initialize-insecure --user=mysql
  args:
    chdir: "{{tdbctl_basedir}}"
    creates: "{{ mysql_data_dir }}/data/ibdata1"
  become: yes
  become_user: mysql
  become_method: su

- name: start tdbctl
  shell: "cd {{tdbctl_basedir}} && ./bin/mysqld_safe --defaults-file={{mysql_conf_dir}}/my.cnf.{{mysql_port}} --user=mysql &"
  args:
    chdir: "{{tdbctl_basedir}}"
    creates: "{{mysql_data_dir}}/mysqld.pid"
  become: yes
  become_user: mysql
  become_method: su
