#- name: Add user mysql
#  script: init_add_user.sh
#  tags:
#    - init_adduser

- name: create mysql user
  user: name=mysql shell=/bin/bash createhome=yes home=/home/mysql expires=-1

- name: set mysql home permissions
  command: chmod 755 /home/mysql

#- name: update sudoers file
#  lineinfile:
#    dest: /etc/sudoers
#    insertafter: EOF
#    line: 'mysql ALL=(ALL) NOPASSWD: ALL'
#    regexp: '^mysql .*'
#    state: present

